### ISSUE TITLE
PDF to XML conversion failed on pdf file .\src\test\resources\Wang_paperAVE2008.pdf

### ISSUE THREAD

**Issue by EasyLOB** [kermitt2/grobid-example#13]
Hi,

I just downloaded and compiled grobid-example, and everything looks fine.
I am using Windows 10 and Java 11.

But when I run the tests I get the folowing error:

```
org.grobid.core.exceptions.GrobidException: [PDFALTO_CONVERSION_FAILURE] PDF to XML conversion failed on pdf file .\src\test\resources\Wang_paperAVE2008.pdf
        at org.grobid.core.document.DocumentSource.processPdfaltoThreadMode(DocumentSource.java:209)
        at org.grobid.core.document.DocumentSource.pdfalto(DocumentSource.java:155)
        at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:64)
        at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:50)
```

The file "Wang_paperAVE2008.pdf" exists.
Just to be sure the code was looking for correct file I changed the file name in TEST code and got the "File not found error", so it's really looking in the right place.

I also changed to another PDF file, but the error is the same.

Any idea what could be the error ?

Thanks

**Comment by EasyLOB** [comment]
I case it's usefull below you find the maven repository for Grobid and the test output:

├───grobid-core
│   └───0.7.1-SNAPSHOT
├───grobid-home
│   └───0.7.1-SNAPSHOT
├───grobid-service
│   └───0.7.1-SNAPSHOT
└───grobid-trainer
    └───0.7.1-SNAPSHOT

D:\_Git_\grobid-example-2>mvn test
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< grobid-example:org.grobidExample >------------------
[INFO] Building grobid-example 0.7.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ org.grobidExample ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources to source/src
[INFO] Copying 1 resource to source
[INFO]
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ org.grobidExample ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to D:\_Git_\grobid-example-2\target\classes
[WARNING] /D:/_Git_/grobid-example-2/src/main/java/org/grobidExample/MyGrobid.java: D:\_Git_\grobid-example-2\src\main\java\org\grobidExample\MyGrobid.java uses or overrides a deprecated API.
[WARNING] /D:/_Git_/grobid-example-2/src/main/java/org/grobidExample/MyGrobid.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ org.grobidExample ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.0:testCompile (default-testCompile) @ org.grobidExample ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to D:\_Git_\grobid-example-2\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ org.grobidExample ---
[INFO] Surefire report directory: D:\_Git_\grobid-example-2\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.grobidExample.TestMyGrobid
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/siegmar/.m2/repository/org/slf4j/slf4j-jdk14/1.7.25/slf4j-jdk14-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/siegmar/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/siegmar/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
out 02, 2021 10:09:29 AM org.grobid.core.main.GrobidHomeFinder getGrobidHomePathOrLoadFromClasspath
WARNING: No Grobid property was provided. Attempting to find Grobid home in the current directory...
out 02, 2021 10:09:29 AM org.grobid.core.main.GrobidHomeFinder findGrobidHomeOrFail
WARNING: ***************************************************************
out 02, 2021 10:09:29 AM org.grobid.core.main.GrobidHomeFinder findGrobidHomeOrFail
WARNING: *** USING GROBID HOME: D:\_Git_\grobid-example-2\..\grobid\grobid-home
out 02, 2021 10:09:29 AM org.grobid.core.main.GrobidHomeFinder findGrobidHomeOrFail
WARNING: ***************************************************************
out 02, 2021 10:09:29 AM org.grobid.core.main.GrobidHomeFinder findGrobidConfigOrFail
WARNING: Grobid config file location was not explicitly set via 'org.grobid.config' system variable, defaulting to: D:\_Git_\grobid-example-2\..\grobid\grobid-home\config\grobid.yaml
out 02, 2021 10:09:29 AM org.grobid.core.main.LibraryLoader load
INFO: Loading external native sequence labelling library
out 02, 2021 10:09:29 AM org.grobid.core.main.LibraryLoader load
INFO: Loading Wapiti native library...
out 02, 2021 10:09:29 AM org.grobid.core.main.LibraryLoader load
INFO: Native library for sequence labelling loaded
out 02, 2021 10:09:29 AM org.grobid.core.lexicon.Lexicon initDictionary
INFO: Initiating dictionary
out 02, 2021 10:09:29 AM org.grobid.core.lexicon.Lexicon initDictionary
INFO: End of Initialization of dictionary
out 02, 2021 10:09:29 AM org.grobid.core.lexicon.Lexicon initNames
INFO: Initiating names
out 02, 2021 10:09:29 AM org.grobid.core.lexicon.Lexicon initNames
INFO: End of initialization of names
out 02, 2021 10:09:29 AM org.grobid.core.lexicon.Lexicon initCountryCodes
INFO: Initiating country codes
out 02, 2021 10:09:29 AM org.grobid.core.lexicon.Lexicon initCountryCodes
INFO: End of initialization of country codes
out 02, 2021 10:09:29 AM org.grobid.core.jni.WapitiModel init
INFO: Loading model: D:\_Git_\grobid-example-2\..\grobid\grobid-home\models\header\model.wapiti (size: 17134253)
org.grobid.core.exceptions.GrobidException: [PDFALTO_CONVERSION_FAILURE] PDF to XML conversion failed on pdf file .\src\test\resources\Wang_paperAVE2008.pdf
        at org.grobid.core.document.DocumentSource.processPdfaltoThreadMode(DocumentSource.java:209)
        at org.grobid.core.document.DocumentSource.pdfalto(DocumentSource.java:155)
        at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:64)
        at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:50)
        at org.grobid.core.engines.HeaderParser.processing(HeaderParser.java:81)
        at org.grobid.core.engines.Engine.processHeader(Engine.java:415)
        at org.grobid.core.engines.Engine.processHeader(Engine.java:400)
        at org.grobidExample.ExampleBibTex.runGrobid(ExampleBibTex.java:50)
        at org.grobidExample.TestMyGrobid.testHeaderBibTeX(TestMyGrobid.java:30)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

out 02, 2021 10:09:32 AM org.grobid.core.jni.WapitiModel init
INFO: Loading model: D:\_Git_\grobid-example-2\..\grobid\grobid-home\models\citation\model.wapiti (size: 16865234)
out 02, 2021 10:09:33 AM org.grobid.core.jni.WapitiModel init
INFO: Loading model: D:\_Git_\grobid-example-2\..\grobid\grobid-home\models\reference-segmenter\model.wapiti (size: 4921245)
org.grobid.core.exceptions.GrobidException: [PDFALTO_CONVERSION_FAILURE] PDF to XML conversion failed on pdf file D:\_Git_\grobid-example-2\.\src\test\resources\Wang_paperAVE2008.pdf
        at org.grobid.core.document.DocumentSource.processPdfaltoThreadMode(DocumentSource.java:209)
        at org.grobid.core.document.DocumentSource.pdfalto(DocumentSource.java:155)
        at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:64)
        at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:50)
        at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:42)
        at org.grobid.core.engines.CitationParser.processingReferenceSection(CitationParser.java:396)
        at org.grobid.core.engines.Engine.processReferences(Engine.java:237)
        at org.grobidExample.ExampleBibTex.runGrobid(ExampleBibTex.java:53)
        at org.grobidExample.TestMyGrobid.testCitationBibTeX(TestMyGrobid.java:42)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

>>>>>>>> GROBID_HOME=D:\_Git_\grobid-example-2\..\grobid\grobid-home
out 02, 2021 10:09:34 AM org.grobid.core.utilities.GrobidProperties getDelftArchitecture
WARNING: No configuration parameter defined for DeLFT engine for model segmentation
out 02, 2021 10:09:34 AM org.grobid.core.jni.WapitiModel init
INFO: Loading model: D:\_Git_\grobid-example-2\..\grobid\grobid-home\models\segmentation\model.wapiti (size: 31133177)
org.grobid.core.exceptions.GrobidException: [GENERAL] An exception occured while running Grobid training data generation for segmentation model.
        at org.grobid.core.engines.Segmentation.createBlankTrainingData(Segmentation.java:781)
        at org.grobid.core.engines.Engine.createTrainingBlank(Engine.java:446)
        at org.grobidExample.MyGrobid.runGrobid(MyGrobid.java:44)
        at org.grobidExample.TestMyGrobid.testHeader(TestMyGrobid.java:20)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.grobid.core.exceptions.GrobidException: [PDFALTO_CONVERSION_FAILURE] PDF to XML conversion failed on pdf file .\src\test\resources\Wang_paperAVE2008.pdf
        at org.grobid.core.document.DocumentSource.processPdfaltoThreadMode(DocumentSource.java:209)
        at org.grobid.core.document.DocumentSource.pdfalto(DocumentSource.java:155)
        at org.grobid.core.document.DocumentSource.fromPdf(DocumentSource.java:64)
        at org.grobid.core.engines.Segmentation.createBlankTrainingData(Segmentation.java:737)
        ... 32 more
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.14 sec <<< FAILURE!
testHeader(org.grobidExample.TestMyGrobid)  Time elapsed: 3.715 sec  <<< FAILURE!
java.lang.AssertionError:
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at org.junit.Assert.assertNotNull(Assert.java:524)
        at org.junit.Assert.assertNotNull(Assert.java:535)
        at org.grobidExample.TestMyGrobid.testHeader(TestMyGrobid.java:21)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

[Wapiti] Loading model: "D:\_Git_\grobid-example-2\..\grobid\grobid-home\models\header\model.wapiti"
Model path: D:\_Git_\grobid-example-2\..\grobid\grobid-home\models\header\model.wapiti
[Wapiti] Loading model: "D:\_Git_\grobid-example-2\..\grobid\grobid-home\models\citation\model.wapiti"
Model path: D:\_Git_\grobid-example-2\..\grobid\grobid-home\models\citation\model.wapiti
[Wapiti] Loading model: "D:\_Git_\grobid-example-2\..\grobid\grobid-home\models\reference-segmenter\model.wapiti"
Model path: D:\_Git_\grobid-example-2\..\grobid\grobid-home\models\reference-segmenter\model.wapiti
[Wapiti] Loading model: "D:\_Git_\grobid-example-2\..\grobid\grobid-home\models\segmentation\model.wapiti"
Model path: D:\_Git_\grobid-example-2\..\grobid\grobid-home\models\segmentation\model.wapiti

Results :

Failed tests:   testHeader(org.grobidExample.TestMyGrobid)

Tests run: 3, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.858 s
[INFO] Finished at: 2021-10-02T10:09:38-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project org.grobidExample: There are test failures.
[ERROR]
[ERROR] Please refer to D:\_Git_\grobid-example-2\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by kermitt2** [comment]
Hello @EasyLOB  !

Thanks for trying GROBID.

As indicated in the GROBID readme and [documentation](https://grobid.readthedocs.io/en/latest/Troubleshooting/#windows-related-issues), Windows is not supported anymore by the latest versions. We did not find the resources and time to build `pdfalto` on Windows in a regular manner, thus the error you see in the PDF to XML conversion. 

You can use the docker image on Windows, it should work very well (with the limitation of using a GPU in case the deep learning docker image is used - as for Windows in general, GPU cannot be used by docker).

**Comment by EasyLOB** [comment]
Hi,
I moved the code to Ubuntu 20.04 and it's compiling and testing perfectly :smile:
Thanks
