### ISSUE TITLE
 java.lang.IllegalAccessError 

### ISSUE THREAD

**Issue by bora0072** [kermitt2/grobid-example#5]
I get the following error when I try to run the example.

Exception in thread "main" java.lang.IllegalAccessError: tried to access field com.cybozu.labs.langdetect.util.LangProfile.name from class com.cybozu.labs.langdetect.DetectorFactory
	at com.cybozu.labs.langdetect.DetectorFactory.addProfile(DetectorFactory.java:123)
	at com.cybozu.labs.langdetect.DetectorFactory.loadProfile(DetectorFactory.java:78)
	at org.grobid.core.lang.impl.CybozuLanguageDetectorFactory.init(CybozuLanguageDetectorFactory.java:31)
	at org.grobid.core.lang.impl.CybozuLanguageDetectorFactory.getNewInstance(CybozuLanguageDetectorFactory.java:50)
	at org.grobid.core.lang.impl.CybozuLanguageDetectorFactory.getInstance(CybozuLanguageDetectorFactory.java:40)
	at org.grobid.core.utilities.LanguageUtilities.runLanguageId(LanguageUtilities.java:82)
	at org.grobid.core.engines.HeaderParser.processingHeaderBlock(HeaderParser.java:145)
	at org.grobid.core.engines.HeaderParser.processing2(HeaderParser.java:104)
	at org.grobid.core.engines.Engine.processHeader(Engine.java:438)
	at org.grobid.core.engines.Engine.processHeader(Engine.java:415)

**Comment by bora0072** [comment]
However If I comment out both the dependencies of com.cybozu.labs, the error magically disappears. I am using grobid-core-0.5.1-SNAPSHOT.jar. I think this dependency is no longer required.

**Comment by kermitt2** [comment]
Hello!

Usually it means that the version of the jar lib used at runtime is different from the one used when compiling, here the lib being the language detection one (com.cybozu.labs).  
Can you try to update the dependencies when compile the project, so
```
mvn clean install -U
```
or maybe cleaning your `.m2/repository/com/cybozu/` and rebuilt
